### ISSUE TITLE
panic when listing exported crds with wildcard logical cluster (missing 'apis.kcp.dev/identity' annotation)

### ISSUE THREAD

**Issue by mikenairn** [kcp-dev/kcp#1038]
**Describe the bug**
After adding a crd to a workspace using an APIBinding, any immediate wildcard requests to list that resource type fail and cause a panic in kcp.

```
$ kubectl get --raw https://192.168.0.67:6443/clusters/*/apis/kuadrant.dev/v1/dnsrecords
Unable to connect to the server: stream error: stream ID 1; INTERNAL_ERROR
```

Server error:
```
E0512 09:18:23.659023 2574017 wrap.go:58] "apiserver panic'd" method="GET" URI="/clusters/%2A/apis/kuadrant.dev/v1/dnsrecords" audit-ID="fd3162b7-b580-4566-861e-ab4d10fdecd5"
http2: panic serving 192.168.0.103:59260: missing 'apis.kcp.dev/identity' annotation
goroutine 51387 [running]:
k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1.1()
	/home/mnairn/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220502152525-1ac78681cb61/pkg/server/filters/timeout.go:105 +0xb0
panic({0x2b00b20, 0xc004417940})
	/home/mnairn/sdk/go1.17.7/src/runtime/panic.go:1038 +0x215
k8s.io/apiextensions-apiserver/pkg/registry/customresource.newREST({{_, _}, {_, _}}, {{0xc004309530, 0xc}, {0xc004309518, 0x2}, {0xc004309e90, 0x9}}, ...)
	/home/mnairn/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiextensions-apiserver@v0.0.0-20220502152525-1ac78681cb61/pkg/registry/customresource/etcd.go:108 +0x73c
...
```

Making a request to a specific logical cluster will work:
```
$ kubectl get --raw https://192.168.0.67:6443/clusters/root:default:kcp-glbc/apis/kuadrant.dev/v1/dnsrecords
{"apiVersion":"kuadrant.dev/v1","items":[],"kind":"DNSRecordList","metadata":{"continue":"","resourceVersion":"344"}}
```

and subsequent wildcard requests from then on will now work:

```
kubectl get --raw https://192.168.0.67:6443/clusters/*/apis/kuadrant.dev/v1/dnsrecords
{"apiVersion":"kuadrant.dev/v1","items":[],"kind":"DNSRecordList","metadata":{"continue":"","resourceVersion":"355"}}
``` 

All wildcard requests fail until you make at least one request to a specific logical cluster. 

**To Reproduce**
1. Start kcp
2. Create a workspace
3. Add an apiresourceschema and apiexport for some CRD(https://github.com/Kuadrant/kcp-glbc/tree/main/utils/kcp-contrib)
4. Create an APIBinding
5. Make a wildcard request to list the resources `kubectl get --raw https://192.168.0.67:6443/clusters/*/apis/kuadrant.dev/v1/dnsrecords`

**Expected behavior**
No panic.

**Additional context**
Only tested on release-0.4 and v0.4.0-alpha.0, i have not tried main yet.

**Comment by sttts** [comment]
This is certainly a bug and should result in some 40x or 50x error. Note that wildcards requests for APIBinding resource need an identity being passed. Compare https://github.com/kcp-dev/kcp/blob/main/test/e2e/apibinding/apibinding_test.go#L194 how this works. cc @ncdc

**Comment by ncdc** [comment]
Will be fully fixed when the apiexport virtual workspace is in. Will look into this in the meantime.

**Comment by ncdc** [comment]
Here is what's happening:

1. Try to do a wildcard list
    1. It finds the CRD in system:bound-crds (it's from an APIExport/APIBinding)
    2. But because it's a wildcard list request without identity (i.e. it's not `/clusters/*/apis/kuadrant.dev/v1/dnsrecords:$identity`), and we don't have the virtual workspace for APIExports implemented yet, we don't know which APIBinding this is for, so we don't know the identity (it could come via multiple APIExport identities)
    3. panic

1. Do a list against a specific logical cluster
    1. This is a non-wildcard request, so it is able to determine the identity, and when it creates the serving info for the CRD, it includes the identity annotation
    2. All subsequent requests, including wildcards, reuse the same serving info, which has the identity
