### ISSUE TITLE
Virtual workspace server panics on create operations

### ISSUE THREAD

**Issue by astefanutti** [kcp-dev/kcp#1253]
**Describe the bug**

When performing a POST request via an APIExport virtual workspace URL, the virtual workspace API server panics with the following stack trace:

```
E0610 17:15:47.184934   34219 wrap.go:58] "apiserver panic'd" method="POST" URI="/services/apiexport/root:default:kcp-glbc/glbc/clusters/root:default:kcp-glbc-user/apis/kuadrant.dev/v1/namespaces/default/dnsrecords" audit-ID="37033e09-4ee4-4531-9624-5355073ba0bf"
http2: panic serving 192.168.0.24:59051: runtime error: invalid memory address or nil pointer dereference
goroutine 318169 [running]:
k8s.io/apiserver/pkg/endpoints/handlers/finisher.finishRequest.func1.1()
        /Users/antonin/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/endpoints/handlers/finisher/finisher.go:105 +0x118
panic({0x49a73c0, 0x67a1690})
        /usr/local/opt/go/libexec/src/runtime/panic.go:844 +0x25a
github.com/kcp-dev/kcp/pkg/virtual/framework/forwardingregistry.CreaterFunc.Create(0x0, {0x5178790, 0xc00ddb3740}, {0x515d008, 0xc00838a3b8}, 0x4f7a0a0, 0xc0153ccba0)
        /Users/antonin/Development/kcp/pkg/virtual/framework/forwardingregistry/functions.go:50 +0x81
k8s.io/apiserver/pkg/endpoints/handlers.(*namedCreaterAdapter).Create(0xc003fe55d0, {0x5178790, 0xc00ddb3740}, {0xc00f739890, 0x11}, {0x515d008, 0xc00838a3b8}, 0x4f7a0a0, 0xc0153ccba0)
        /Users/antonin/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/endpoints/handlers/create.go:237 +0xd3
k8s.io/apiserver/pkg/endpoints/handlers.createHandler.func1.1()
        /Users/antonin/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/endpoints/handlers/create.go:169 +0x153
k8s.io/apiserver/pkg/endpoints/handlers.createHandler.func1.2()
        /Users/antonin/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/endpoints/handlers/create.go:195 +0x616
k8s.io/apiserver/pkg/endpoints/handlers/finisher.finishRequest.func1()
        /Users/antonin/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/endpoints/handlers/finisher/finisher.go:117 +0x10b
created by k8s.io/apiserver/pkg/endpoints/handlers/finisher.finishRequest
        /Users/antonin/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/endpoints/handlers/finisher/finisher.go:92 +0x105

goroutine 318339 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x48766e0, 0xc0133a0760})
        /Users/antonin/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/util/runtime/runtime.go:74 +0x105
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0xc00aa2a038, 0x1, 0x1})
        /Users/antonin/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/util/runtime/runtime.go:48 +0xc2
panic({0x48766e0, 0xc0133a0760})
        /usr/local/opt/go/libexec/src/runtime/panic.go:844 +0x25a
k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc000698ed0, {0x51779c0, 0xc00b070000}, 0xc013608400)
        /Users/antonin/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/server/filters/timeout.go:116 +0x4df
k8s.io/apiserver/pkg/endpoints/filters.withRequestDeadline.func1({0x5169890, 0xc00828c140}, 0xc013608400)
        /Users/antonin/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/endpoints/filters/request_deadline.go:100 +0x6ac
net/http.HandlerFunc.ServeHTTP(0xc001b6de30, {0x5169890, 0xc00828c140}, 0xc013608300)
        /usr/local/opt/go/libexec/src/net/http/server.go:2084 +0x43
k8s.io/apiserver/pkg/server/filters.withWaitGroup.func1({0x5169890, 0xc00828c140}, 0xc013608300)
        /Users/antonin/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/server/filters/waitgroup.go:77 +0x6cc
net/http.HandlerFunc.ServeHTTP(0xc00239e720, {0x5169890, 0xc00828c140}, 0xc013608300)
        /usr/local/opt/go/libexec/src/net/http/server.go:2084 +0x43
k8s.io/apiserver/pkg/endpoints/filters.WithWarningRecorder.func1({0x5169890, 0xc00828c140}, 0xc013608300)
        /Users/antonin/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/endpoints/filters/warning.go:35 +0x15a
net/http.HandlerFunc.ServeHTTP(0xc000698ee8, {0x5169890, 0xc00828c140}, 0xc013608200)
        /usr/local/opt/go/libexec/src/net/http/server.go:2084 +0x43
k8s.io/apiserver/pkg/endpoints/filters.WithCacheControl.func1({0x5169890, 0xc00828c140}, 0xc013608200)
        /Users/antonin/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/endpoints/filters/cachecontrol.go:31 +0xd5
net/http.HandlerFunc.ServeHTTP(0xc000698f00, {0x5169890, 0xc00828c140}, 0xc013608200)
        /usr/local/opt/go/libexec/src/net/http/server.go:2084 +0x43
k8s.io/apiserver/pkg/server/httplog.withLogging.func1({0x5169890, 0xc00828c140}, 0xc013608200)
        /Users/antonin/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/server/httplog/httplog.go:108 +0x374
net/http.HandlerFunc.ServeHTTP(0xc00239e750, {0x5169890, 0xc00828c140}, 0xc013608200)
        /usr/local/opt/go/libexec/src/net/http/server.go:2084 +0x43
k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1({0x5169890, 0xc00828c140}, 0xc013608200)
        /Users/antonin/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/endpoints/filters/requestinfo.go:39 +0x269
net/http.HandlerFunc.ServeHTTP(0xc00239e780, {0x5169890, 0xc00828c140}, 0xc013608100)
        /usr/local/opt/go/libexec/src/net/http/server.go:2084 +0x43
k8s.io/apiserver/pkg/endpoints/filters.withRequestReceivedTimestampWithClock.func1({0x5169890, 0xc00828c140}, 0xc013608100)
        /Users/antonin/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/endpoints/filters/request_received_time.go:38 +0x11d
net/http.HandlerFunc.ServeHTTP(0xc00239e7b0, {0x5169890, 0xc00828c140}, 0xc013608000)
        /usr/local/opt/go/libexec/src/net/http/server.go:2084 +0x43
k8s.io/apiserver/pkg/endpoints/filters.WithMuxAndDiscoveryComplete.func1({0x5169890, 0xc00828c140}, 0xc013608000)
        /Users/antonin/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/endpoints/filters/mux_discovery_complete.go:52 +0x111
net/http.HandlerFunc.ServeHTTP(0xc0024e06a0, {0x5169890, 0xc00828c140}, 0xc00c761f00)
        /usr/local/opt/go/libexec/src/net/http/server.go:2084 +0x43
k8s.io/apiserver/pkg/server/filters.withPanicRecovery.func1({0x5169890, 0xc00828c140}, 0xc00c761f00)
        /Users/antonin/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/server/filters/wrap.go:74 +0x17f
net/http.HandlerFunc.ServeHTTP(0xc0024e06c0, {0x5169890, 0xc00828c140}, 0xc00c761f00)
        /usr/local/opt/go/libexec/src/net/http/server.go:2084 +0x43
k8s.io/apiserver/pkg/endpoints/filters.withAuditID.func1({0x5169890, 0xc00828c140}, 0xc00c761f00)
        /Users/antonin/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/endpoints/filters/with_auditid.go:66 +0x1cc
net/http.HandlerFunc.ServeHTTP(0xc0024e06e0, {0x5169890, 0xc00828c140}, 0xc00c761e00)
        /usr/local/opt/go/libexec/src/net/http/server.go:2084 +0x43
github.com/kcp-dev/kcp/pkg/virtual/framework/rootapiserver.completedConfig.getRootHandlerChain.func1.2({0x5169890, 0xc00828c140}, 0xc00c761e00)
        /Users/antonin/Development/kcp/pkg/virtual/framework/rootapiserver/root_apiserver.go:178 +0x288
net/http.HandlerFunc.ServeHTTP(0xc00239e7e0, {0x5169890, 0xc00828c140}, 0xc00c761d00)
        /usr/local/opt/go/libexec/src/net/http/server.go:2084 +0x43
k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc000adf540, {0x5169890, 0xc00828c140}, 0xc00c761d00)
        /Users/antonin/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/server/handler.go:197 +0x43
net/http.(*ServeMux).ServeHTTP(0xc003784b40, {0x5169890, 0xc00828c140}, 0xc00c761d00)
        /usr/local/opt/go/libexec/src/net/http/server.go:2462 +0x135
github.com/kcp-dev/kcp/pkg/server.WithWorkspaceProjection.func1({0x5169890, 0xc00828c140}, 0xc00c761d00)
        /Users/antonin/Development/kcp/pkg/server/handler.go:204 +0x548
net/http.HandlerFunc.ServeHTTP(0xc00376b770, {0x5169890, 0xc00828c140}, 0xc00c761d00)
        /usr/local/opt/go/libexec/src/net/http/server.go:2084 +0x43
github.com/kcp-dev/kcp/pkg/server.WithClusterAnnotation.func1({0x5169890, 0xc00828c140}, 0xc00c761d00)
        /Users/antonin/Development/kcp/pkg/server/handler.go:182 +0x104
net/http.HandlerFunc.ServeHTTP(0xc000af95c0, {0x5169890, 0xc00828c140}, 0xc00c761d00)
        /usr/local/opt/go/libexec/src/net/http/server.go:2084 +0x43
github.com/kcp-dev/kcp/pkg/server.WithAuditAnnotation.func1({0x5169890, 0xc00828c140}, 0xc004cdfc00)
        /Users/antonin/Development/kcp/pkg/server/handler.go:167 +0xa4
net/http.HandlerFunc.ServeHTTP(0xc000af95d8, {0x5169890, 0xc00828c140}, 0xc004cdfc00)
        /usr/local/opt/go/libexec/src/net/http/server.go:2084 +0x43
github.com/kcp-dev/kcp/pkg/server.WithClusterScope.func1({0x5169890, 0xc00828c140}, 0xc004cdf200)
        /Users/antonin/Development/kcp/pkg/server/handler.go:159 +0x864
net/http.HandlerFunc.ServeHTTP(0xc000af95f0, {0x5169890, 0xc00828c140}, 0xc004cdf200)
        /usr/local/opt/go/libexec/src/net/http/server.go:2084 +0x43
github.com/kcp-dev/kcp/pkg/server.WithInClusterServiceAccountRequestRewrite.func1({0x5169890, 0xc00828c140}, 0xc004cdf200)
        /Users/antonin/Development/kcp/pkg/server/handler.go:263 +0x294
net/http.HandlerFunc.ServeHTTP(0xc00376b7a0, {0x5169890, 0xc00828c140}, 0xc004cdf200)
        /usr/local/opt/go/libexec/src/net/http/server.go:2084 +0x43
github.com/kcp-dev/kcp/pkg/server.WithAcceptHeader.func1({0x5169890, 0xc00828c140}, 0xc005f1bd00)
        /Users/antonin/Development/kcp/pkg/server/handler.go:88 +0x123
net/http.HandlerFunc.ServeHTTP(0xc000af9608, {0x5169890, 0xc00828c140}, 0xc005f1bd00)
        /usr/local/opt/go/libexec/src/net/http/server.go:2084 +0x43
k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc003784b80, {0x5169890, 0xc00828c140}, 0xc005f1bd00)
        /Users/antonin/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/server/handler.go:197 +0x43
net/http.serverHandler.ServeHTTP({0xc0009c4d20}, {0x5169890, 0xc00828c140}, 0xc005f1bd00)
        /usr/local/opt/go/libexec/src/net/http/server.go:2916 +0x474
net/http.initALPNRequest.ServeHTTP({{0x5178790, 0xc00ba87a40}, 0xc00abdc700, {0xc0009c4d20}}, {0x5169890, 0xc00828c140}, 0xc005f1bd00)
        /usr/local/opt/go/libexec/src/net/http/server.go:3523 +0x293
golang.org/x/net/http2.(*serverConn).runHandler(0xc00b47f080, 0xc00828c140, 0xc005f1bd00, 0xc008592e70)
        /Users/antonin/go/pkg/mod/golang.org/x/net@v0.0.0-20211209124913-491a49abca63/http2/server.go:2184 +0xe8
created by golang.org/x/net/http2.(*serverConn).processHeaders
        /Users/antonin/go/pkg/mod/golang.org/x/net@v0.0.0-20211209124913-491a49abca63/http2/server.go:1914 +0xa85
```

**To Reproduce**

1. Create an APIExport in workspace A
2. Create an APIBinding in workspace B, referencing APIExport from workspace A
3. Create a resource in workspace B using the APIExport virtual workspace URL 

**Expected behavior**

Ideally, create requests should be supported, or at least a better response should be returned, rather than panicking.

**Additional context**

The `nil` dereference happens at:
https://github.com/kcp-dev/kcp/blob/7957a59c49bfbe3871022566f8d1c8dc078260a4/pkg/virtual/framework/forwardingregistry/functions.go#L50

Which is induced by:
https://github.com/kcp-dev/kcp/blob/7957a59c49bfbe3871022566f8d1c8dc078260a4/pkg/virtual/framework/forwardingregistry/store.go#L90

**Comment by sttts** [comment]
@stevekuznetsov @davidfestal

**Comment by sttts** [comment]
Create requests are supposed to be supported. If not that's a bug.

**Comment by astefanutti** [comment]
@stevekuznetsov I just assumed it would work initially.

I haven't managed to successfully call discovery via the APIExport virtual workspace server, neither via command nor client-go, e.g., with the CLI:

```console
$ kubectl --cluster workspace.kcp.dev/virtual api-resources --v=9
I0613 18:56:59.665419   60344 loader.go:372] Config loaded from file:  .kcp/admin.kubeconfig
I0613 18:56:59.666745   60344 round_trippers.go:466] curl -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.23.4 (darwin/amd64) kubernetes/e6c093d" -H "Authorization: Bearer <masked>" 'https://192.168.0.24:6443/services/apiexport/root:default:kcp-glbc-user-compute/kubernetes/api?timeout=32s'
I0613 18:56:59.667921   60344 round_trippers.go:510] HTTP Trace: Dial to tcp:192.168.0.24:6443 succeed
I0613 18:56:59.681684   60344 round_trippers.go:570] HTTP Statistics: DNSLookup 0 ms Dial 0 ms TLSHandshake 3 ms ServerProcessing 0 ms Duration 14 ms
I0613 18:56:59.681712   60344 round_trippers.go:577] Response Headers:
I0613 18:56:59.681727   60344 round_trippers.go:580]     Cache-Control: no-cache, private
I0613 18:56:59.681734   60344 round_trippers.go:580]     Content-Type: text/plain; charset=utf-8
I0613 18:56:59.681740   60344 round_trippers.go:580]     X-Content-Type-Options: nosniff
I0613 18:56:59.681745   60344 round_trippers.go:580]     Content-Length: 19
I0613 18:56:59.681751   60344 round_trippers.go:580]     Date: Mon, 13 Jun 2022 16:56:59 GMT
I0613 18:56:59.681757   60344 round_trippers.go:580]     Audit-Id: 83e91be1-7bf9-47b2-bee2-0156fa1f4f7f
I0613 18:56:59.808241   60344 request.go:1181] Response Body: 404 page not found
I0613 18:56:59.879301   60344 request.go:1372] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
I0613 18:56:59.879369   60344 round_trippers.go:466] curl -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.23.4 (darwin/amd64) kubernetes/e6c093d" -H "Authorization: Bearer <masked>" 'https://192.168.0.24:6443/services/apiexport/root:default:kcp-glbc-user-compute/kubernetes/apis?timeout=32s'
I0613 18:56:59.898435   60344 round_trippers.go:570] HTTP Statistics: GetConnection 0 ms ServerProcessing 0 ms Duration 19 ms
I0613 18:56:59.898451   60344 round_trippers.go:577] Response Headers:
I0613 18:56:59.898457   60344 round_trippers.go:580]     Cache-Control: no-cache, private
I0613 18:56:59.898463   60344 round_trippers.go:580]     Content-Type: text/plain; charset=utf-8
I0613 18:56:59.898471   60344 round_trippers.go:580]     X-Content-Type-Options: nosniff
I0613 18:56:59.898478   60344 round_trippers.go:580]     Content-Length: 19
I0613 18:56:59.898483   60344 round_trippers.go:580]     Date: Mon, 13 Jun 2022 16:56:59 GMT
I0613 18:56:59.898488   60344 round_trippers.go:580]     Audit-Id: dd410d2e-db9f-43a0-85e1-e67ac07a8d25
I0613 18:56:59.917708   60344 request.go:1181] Response Body: 404 page not found
I0613 18:56:59.953808   60344 request.go:1372] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
I0613 18:56:59.954715   60344 cached_discovery.go:125] skipped caching discovery info, no groups found
```

**Comment by stevekuznetsov** [comment]
There seem to be three issues here:

 - [ ] when no CREATE function is registered, we should not have a CREATE verb and we should return a not-supported HTTP code
 - [ ] you should be able to do discovery (and e2e seems to support this)
 - [ ] APIExport virtual workspace should support CREATE (missing feature)

**Comment by stevekuznetsov** [comment]
Ah - as seen [here](https://github.com/kcp-dev/kcp/blob/b842cbad598d4985f809c7715076ed3216e2e4ad/pkg/virtual/apiexport/builder/forwarding.go#L128) we are passing through a CREATE function, even though it's `nil`. This should mean that we *do* panic, and CREATE *should* be in discovery - so I'd say we can fix this either by implementing CREATE in one shot, or removing the function for now so the server returns a not supported error instead of panic, until we implement CREATE in the future.

**Comment by astefanutti** [comment]
An update on the issues identified:
* [x]  when no CREATE function is registered, we should not have a CREATE verb and we should return a not-supported HTTP code -> Fixed with #1272
* [x]  you should be able to do discovery (and e2e seems to support this): This is indeed working (I was actually calling the APIExport virtual workspace URL without appending the logical cluster path) 
* [ ]  APIExport virtual workspace should support CREATE (missing feature): I'll work on it ASAP.
