### ISSUE TITLE
We Double-Register Endpoints

### ISSUE THREAD

**Issue by stevekuznetsov** [kcp-dev/kcp#1259]
```
E0613 07:35:09.467116  188627 pathrecorder.go:109] duplicate path registration of "/readyz/ping": original registration from goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).trackCallers(0xc000b533b0, {0xc000ffe1a0, 0xc})
	/home/stevekuznetsov/code/kcp-dev/kcp/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/server/mux/pathrecorder.go:107 +0x45
k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).Handle(0xc000b533b0, {0xc000ffe1a0, 0xc}, {0x34f11c0?, 0xc0046fba10})
	/home/stevekuznetsov/code/kcp-dev/kcp/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/server/mux/pathrecorder.go:175 +0xc9
k8s.io/apiserver/pkg/server/healthz.InstallPathHandlerWithHealthyFunc({0x34ed3e0, 0xc000b533b0}, {0x2f37964, 0x7}, 0xc0016df600?, {0xc00145b800?, 0x2b?, 0xc000e0a3f8?})
	/home/stevekuznetsov/code/kcp-dev/kcp/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/server/healthz/healthz.go:189 +0x5a3
k8s.io/apiserver/pkg/server/healthz.InstallReadyzHandlerWithHealthyFunc(...)
	/home/stevekuznetsov/code/kcp-dev/kcp/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/server/healthz/healthz.go:146
k8s.io/apiserver/pkg/server.(*GenericAPIServer).installReadyz(0xc002bb5b80?)
	/home/stevekuznetsov/code/kcp-dev/kcp/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/server/healthz.go:106 +0x11a
k8s.io/apiserver/pkg/server.(*GenericAPIServer).PrepareRun(0xc002bb5b80)
	/home/stevekuznetsov/code/kcp-dev/kcp/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/server/genericapiserver.go:400 +0x25b
github.com/kcp-dev/kcp/pkg/server.(*Server).Run(0xc00094c3f0, {0x35131a8, 0xc0009cc9c0})
	/home/stevekuznetsov/code/kcp-dev/kcp/src/github.com/kcp-dev/kcp/pkg/server/server.go:505 +0x20e5
main.main.func2(0xc00027b900?, {0x2f3404d?, 0xa?, 0xa?})
	/home/stevekuznetsov/code/kcp-dev/kcp/src/github.com/kcp-dev/kcp/cmd/kcp/kcp.go:105 +0x108
github.com/spf13/cobra.(*Command).execute(0xc00027b900, {0xc00110c6e0, 0xa, 0xa})
	/home/stevekuznetsov/code/kcp-dev/kcp/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc00027b400)
	/home/stevekuznetsov/code/kcp-dev/kcp/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/home/stevekuznetsov/code/kcp-dev/kcp/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
	/home/stevekuznetsov/code/kcp-dev/kcp/src/github.com/kcp-dev/kcp/cmd/kcp/kcp.go:148 +0x58c


new registration from goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).trackCallers(0xc000b533b0, {0xc000ffe1d0, 0xc})
	/home/stevekuznetsov/code/kcp-dev/kcp/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/server/mux/pathrecorder.go:107 +0x45
k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).Handle(0xc000b533b0, {0xc000ffe1d0, 0xc}, {0x34f11c0?, 0xc0047361f0})
	/home/stevekuznetsov/code/kcp-dev/kcp/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/server/mux/pathrecorder.go:175 +0xc9
k8s.io/apiserver/pkg/server/healthz.InstallPathHandlerWithHealthyFunc({0x34ed3e0, 0xc000b533b0}, {0x2f37964, 0x7}, 0xc0016df600?, {0xc00145b800?, 0x2b?, 0xc000e0a3f8?})
	/home/stevekuznetsov/code/kcp-dev/kcp/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/server/healthz/healthz.go:189 +0x5a3
k8s.io/apiserver/pkg/server/healthz.InstallReadyzHandlerWithHealthyFunc(...)
	/home/stevekuznetsov/code/kcp-dev/kcp/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/server/healthz/healthz.go:146
k8s.io/apiserver/pkg/server.(*GenericAPIServer).installReadyz(0xc002bb5b80?)
	/home/stevekuznetsov/code/kcp-dev/kcp/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/server/healthz.go:106 +0x11a
k8s.io/apiserver/pkg/server.(*GenericAPIServer).PrepareRun(0xc002bb5b80)
	/home/stevekuznetsov/code/kcp-dev/kcp/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/server/genericapiserver.go:400 +0x25b
github.com/kcp-dev/kcp/pkg/server.(*Server).Run(0xc00094c3f0, {0x35131a8, 0xc0009cc9c0})
	/home/stevekuznetsov/code/kcp-dev/kcp/src/github.com/kcp-dev/kcp/pkg/server/server.go:505 +0x20e5
main.main.func2(0xc00027b900?, {0x2f3404d?, 0xa?, 0xa?})
	/home/stevekuznetsov/code/kcp-dev/kcp/src/github.com/kcp-dev/kcp/cmd/kcp/kcp.go:105 +0x108
github.com/spf13/cobra.(*Command).execute(0xc00027b900, {0xc00110c6e0, 0xa, 0xa})
	/home/stevekuznetsov/code/kcp-dev/kcp/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc00027b400)
	/home/stevekuznetsov/code/kcp-dev/kcp/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/home/stevekuznetsov/code/kcp-dev/kcp/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
	/home/stevekuznetsov/code/kcp-dev/kcp/src/github.com/kcp-dev/kcp/cmd/kcp/kcp.go:148 +0x58c
E0613 07:35:09.467230  188627 pathrecorder.go:109] duplicate path registration of "/readyz/log": original registration from goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).trackCallers(0xc000b533b0, {0xc000ffe1b0, 0xb})
	/home/stevekuznetsov/code/kcp-dev/kcp/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/server/mux/pathrecorder.go:107 +0x45
k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).Handle(0xc000b533b0, {0xc000ffe1b0, 0xb}, {0x34f11c0?, 0xc0046fba70})
	/home/stevekuznetsov/code/kcp-dev/kcp/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/server/mux/pathrecorder.go:175 +0xc9
k8s.io/apiserver/pkg/server/healthz.InstallPathHandlerWithHealthyFunc({0x34ed3e0, 0xc000b533b0}, {0x2f37964, 0x7}, 0xc0016df600?, {0xc00145b800?, 0x2b?, 0xc000e0a3f8?})
	/home/stevekuznetsov/code/kcp-dev/kcp/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/server/healthz/healthz.go:189 +0x5a3
k8s.io/apiserver/pkg/server/healthz.InstallReadyzHandlerWithHealthyFunc(...)
	/home/stevekuznetsov/code/kcp-dev/kcp/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/server/healthz/healthz.go:146
k8s.io/apiserver/pkg/server.(*GenericAPIServer).installReadyz(0xc002bb5b80?)
	/home/stevekuznetsov/code/kcp-dev/kcp/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/server/healthz.go:106 +0x11a
k8s.io/apiserver/pkg/server.(*GenericAPIServer).PrepareRun(0xc002bb5b80)
	/home/stevekuznetsov/code/kcp-dev/kcp/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/server/genericapiserver.go:400 +0x25b
github.com/kcp-dev/kcp/pkg/server.(*Server).Run(0xc00094c3f0, {0x35131a8, 0xc0009cc9c0})
	/home/stevekuznetsov/code/kcp-dev/kcp/src/github.com/kcp-dev/kcp/pkg/server/server.go:505 +0x20e5
main.main.func2(0xc00027b900?, {0x2f3404d?, 0xa?, 0xa?})
	/home/stevekuznetsov/code/kcp-dev/kcp/src/github.com/kcp-dev/kcp/cmd/kcp/kcp.go:105 +0x108
github.com/spf13/cobra.(*Command).execute(0xc00027b900, {0xc00110c6e0, 0xa, 0xa})
	/home/stevekuznetsov/code/kcp-dev/kcp/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc00027b400)
	/home/stevekuznetsov/code/kcp-dev/kcp/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/home/stevekuznetsov/code/kcp-dev/kcp/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
	/home/stevekuznetsov/code/kcp-dev/kcp/src/github.com/kcp-dev/kcp/cmd/kcp/kcp.go:148 +0x58c


new registration from goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).trackCallers(0xc000b533b0, {0xc000ffe1e0, 0xb})
	/home/stevekuznetsov/code/kcp-dev/kcp/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/server/mux/pathrecorder.go:107 +0x45
k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).Handle(0xc000b533b0, {0xc000ffe1e0, 0xb}, {0x34f11c0?, 0xc0047362a0})
	/home/stevekuznetsov/code/kcp-dev/kcp/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/server/mux/pathrecorder.go:175 +0xc9
k8s.io/apiserver/pkg/server/healthz.InstallPathHandlerWithHealthyFunc({0x34ed3e0, 0xc000b533b0}, {0x2f37964, 0x7}, 0xc0016df600?, {0xc00145b800?, 0x2b?, 0xc000e0a3f8?})
	/home/stevekuznetsov/code/kcp-dev/kcp/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/server/healthz/healthz.go:189 +0x5a3
k8s.io/apiserver/pkg/server/healthz.InstallReadyzHandlerWithHealthyFunc(...)
	/home/stevekuznetsov/code/kcp-dev/kcp/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/server/healthz/healthz.go:146
k8s.io/apiserver/pkg/server.(*GenericAPIServer).installReadyz(0xc002bb5b80?)
	/home/stevekuznetsov/code/kcp-dev/kcp/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/server/healthz.go:106 +0x11a
k8s.io/apiserver/pkg/server.(*GenericAPIServer).PrepareRun(0xc002bb5b80)
	/home/stevekuznetsov/code/kcp-dev/kcp/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220524063253-5bb0eeecf2cf/pkg/server/genericapiserver.go:400 +0x25b
github.com/kcp-dev/kcp/pkg/server.(*Server).Run(0xc00094c3f0, {0x35131a8, 0xc0009cc9c0})
	/home/stevekuznetsov/code/kcp-dev/kcp/src/github.com/kcp-dev/kcp/pkg/server/server.go:505 +0x20e5
main.main.func2(0xc00027b900?, {0x2f3404d?, 0xa?, 0xa?})
	/home/stevekuznetsov/code/kcp-dev/kcp/src/github.com/kcp-dev/kcp/cmd/kcp/kcp.go:105 +0x108
github.com/spf13/cobra.(*Command).execute(0xc00027b900, {0xc00110c6e0, 0xa, 0xa})
	/home/stevekuznetsov/code/kcp-dev/kcp/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc00027b400)
	/home/stevekuznetsov/code/kcp-dev/kcp/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/home/stevekuznetsov/code/kcp-dev/kcp/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
	/home/stevekuznetsov/code/kcp-dev/kcp/src/github.com/kcp-dev/kcp/cmd/kcp/kcp.go:148 +0x58c
```

**Comment by p0lyn0mial** [comment]
fixed https://github.com/kcp-dev/kcp/pull/1273
