### ISSUE TITLE
WaitForClusterReady panics

### ISSUE THREAD

**Issue by sttts** [kcp-dev/kcp#1604]
```
        fixture.go:848: running: kubectl --kubeconfig /Users/sts/Quellen/origin/src/github.com/kcp-dev/kcp/kind.kubeconfig -n kcp-syncer-kubelike-dsjr27pl logs kcp-syncer-kubelike-dsjr27pl-744db5bcfd-4l68t
        fixture.go:572: Deleting syncer resources for logical cluster "root:e2e-org-qfw44:e2e-workspace-g68s6", sync target "kubelike"
        fixture.go:586: Deleting synced resources for logical cluster "root:e2e-org-qfw44:e2e-workspace-g68s6", sync target "kubelike"
        fixture.go:504: Collecting imported resource info: /Users/sts/Quellen/origin/src/github.com/kcp-dev/kcp/artifacts/TestSyncerVirtualWorkspace/access_kcp_resources_through_syncer_virtual_workspace/2321635914/artifacts
        fixture.go:513: Error gathering apps/v1, Resource=deployments: the server could not find the requested resource
panic: interface conversion: interface {} is time.Duration, not string [recovered]
	panic: interface conversion: interface {} is time.Duration, not string

goroutine 206 [running]:
testing.tRunner.func1.2({0x106e82b60, 0xc000c7d9e0})
	/Users/sts/.bin/go-1.18/src/testing/testing.go:1389 +0x278
testing.tRunner.func1()
	/Users/sts/.bin/go-1.18/src/testing/testing.go:1392 +0x420
panic({0x106e82b60, 0xc000c7d9e0})
	/Users/sts/.bin/go-1.18/src/runtime/panic.go:844 +0x258
github.com/stretchr/testify/assert.messageFromMsgAndArgs({0xc000fb6fd8, 0x5, 0x5})
	/Users/sts/Quellen/origin/pkg/mod/github.com/stretchr/testify@v1.7.1/assert/assertions.go:191 +0x194
github.com/stretchr/testify/assert.Fail({0x1121c8838, 0xc000603d40}, {0x105f99026, 0x19}, {0xc000fb6fd8, 0x5, 0x5})
	/Users/sts/Quellen/origin/pkg/mod/github.com/stretchr/testify@v1.7.1/assert/assertions.go:257 +0x1cc
github.com/stretchr/testify/assert.Eventually({0x1121c8838, 0xc000603d40}, 0xc0006b7d00, 0x0?, 0xc0006b7d00?, {0xc000fb6fd8, 0x5, 0x5})
	/Users/sts/Quellen/origin/pkg/mod/github.com/stretchr/testify@v1.7.1/assert/assertions.go:1688 +0x304
github.com/stretchr/testify/require.Eventually({0x1072ff4f8, 0xc000603d40}, 0x0?, 0x18?, 0x1121a02d8?, {0xc0009acfd8, 0x5, 0x5})
	/Users/sts/Quellen/origin/pkg/mod/github.com/stretchr/testify@v1.7.1/require/require.go:361 +0x98
github.com/kcp-dev/kcp/test/e2e/framework.Eventually(0xc000603d40, 0xc0004f76e0, 0x6fc23ac00, 0xc000603d40?, {0xc0009acfd8, 0x5, 0x5})
	/Users/sts/Quellen/origin/src/github.com/kcp-dev/kcp/test/e2e/framework/util.go:301 +0x1fc
github.com/kcp-dev/kcp/test/e2e/framework.EventuallyReady(0xc000603d40, 0xc000d5a420, {0xc0009acfd8, 0x5, 0x5})
	/Users/sts/Quellen/origin/src/github.com/kcp-dev/kcp/test/e2e/framework/util.go:320 +0x114
github.com/kcp-dev/kcp/test/e2e/framework.(*StartedSyncerFixture).WaitForClusterReady(0xc000d569a0, 0xc000603d40, {0x1073160e0?, 0xc001066800})
	/Users/sts/Quellen/origin/src/github.com/kcp-dev/kcp/test/e2e/framework/fixture.go:648 +0x314
github.com/kcp-dev/kcp/test/e2e/framework.SyncerFixture.Start({0xc0010941e0, {0x10731d980, 0xc0001a29b0}, {{0xc0003a81e0, 0x26}}, {{0x0, 0x0}}, {0x105f6db8c, 0x8}, {0x0, ...}, ...}, ...)
	/Users/sts/Quellen/origin/src/github.com/kcp-dev/kcp/test/e2e/framework/fixture.go:625 +0x10f8
github.com/kcp-dev/kcp/test/e2e/virtual/syncer.TestSyncerVirtualWorkspace.func5(0xc000603d40)
	/Users/sts/Quellen/origin/src/github.com/kcp-dev/kcp/test/e2e/virtual/syncer/virtualworkspace_test.go:590 +0x2bc
testing.tRunner(0xc000603d40, 0xc0003cfd60)
	/Users/sts/.bin/go-1.18/src/testing/testing.go:1439 +0x190
created by testing.(*T).Run
	/Users/sts/.bin/go-1.18/src/testing/testing.go:1486 +0x564
```

**Comment by sttts** [comment]
fixed in rebase PR
