### ISSUE TITLE
bug: API server panics on SelfSubjectRulesReview requests

### ISSUE THREAD

**Issue by astefanutti** [kcp-dev/kcp#1924]
### Describe the bug

SSR requests to a workspace API server return abruptly.

The stack trace points to the `github.com/kcp-dev/kcp/pkg/authorization.(*LocalAuthorizer).RulesFor` method:
```
E0908 20:41:51.897726   84042 wrap.go:57] "apiserver panic'd" method="POST" URI="/clusters/root:camel-k:demo/apis/authorization.k8s.io/v1/selfsubjectrulesreviews" audit-ID="fc6f0ebc-24da-4945-b682-15749be88389"
http2: panic serving 192.168.0.24:50693: implement me
goroutine 405181 [running]:
k8s.io/apiserver/pkg/endpoints/handlers/finisher.finishRequest.func1.1()
        /Users/antonin/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220901103730-c8d74a9d456b/pkg/endpoints/handlers/finisher/finisher.go:105 +0x118
panic({0x7d19680, 0x86e7a90})
        /usr/local/opt/go/libexec/src/runtime/panic.go:890 +0x267
github.com/kcp-dev/kcp/pkg/authorization.(*LocalAuthorizer).RulesFor(0xc0003ca190, {0x872e7e8, 0xc00b49f800}, {0xc01e6f08c8, 0x7})
        /Users/antonin/Development/kcp/pkg/authorization/local_authorizer.go:65 +0x6f
k8s.io/apiserver/pkg/authorization/union.unionAuthzRulesHandler.RulesFor({0xc000133640, 0x2, 0x2}, {0x872e7e8, 0xc00b49f800}, {0xc01e6f08c8, 0x7})
        /Users/antonin/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220901103730-c8d74a9d456b/pkg/authorization/union/union.go:89 +0x2f9
k8s.io/kubernetes/pkg/registry/authorization/selfsubjectrulesreview.(*REST).Create(0xc001061c70, {0x872d358, 0xc01ef32ab0}, {0x87148c8, 0xc018ffb980}, 0xc01c2ba940, 0xc01685a3c0)
        /Users/antonin/go/pkg/mod/github.com/kcp-dev/kubernetes@v0.0.0-20220901103730-c8d74a9d456b/pkg/registry/authorization/selfsubjectrulesreview/rest.go:81 +0x2f1
k8s.io/apiserver/pkg/endpoints/handlers.(*namedCreaterAdapter).Create(0xc01e9e2c10, {0x872d358, 0xc01ef32ab0}, {0x0, 0x0}, {0x87148c8, 0xc018ffb980}, 0xc01c2ba940, 0xc01685a3c0)
        /Users/antonin/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220901103730-c8d74a9d456b/pkg/endpoints/handlers/create.go:247 +0xd3
k8s.io/apiserver/pkg/endpoints/handlers.createHandler.func1.1()
        /Users/antonin/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220901103730-c8d74a9d456b/pkg/endpoints/handlers/create.go:177 +0x153
k8s.io/apiserver/pkg/endpoints/handlers.createHandler.func1.2()
        /Users/antonin/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220901103730-c8d74a9d456b/pkg/endpoints/handlers/create.go:203 +0x622
k8s.io/apiserver/pkg/endpoints/handlers/finisher.finishRequest.func1()
        /Users/antonin/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220901103730-c8d74a9d456b/pkg/endpoints/handlers/finisher/finisher.go:117 +0x10b
created by k8s.io/apiserver/pkg/endpoints/handlers/finisher.finishRequest
        /Users/antonin/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220901103730-c8d74a9d456b/pkg/endpoints/handlers/finisher/finisher.go:92 +0x10a
```

### Steps To Reproduce

```
$ curl -v -k \
    -X POST \
    -d @- \
    -H "Authorization: Bearer <REDACTED>" \
    -H 'Accept: application/json' \
    -H 'Content-Type: application/json' \
    https://192.168.0.24:6443/clusters/root:default:test/apis/authorization.k8s.io/v1/selfsubjectrulesreviews <<'EOF'
{
  "kind": "SelfSubjectRulesReview",
  "apiVersion": "authorization.k8s.io/v1",
  "spec": {
    "namespace": "default"
  }
}
EOF
* HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
* stopped the pause stream!
* Connection #0 to host 192.168.0.24 left intact
curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
```

### Expected Behaviour

It should be possible to perform SSR requests.

### Additional Context

SAR requests return successfully, e.g.:

```
$ curl -v -k \
    -X POST \
    -d @- \
    -H "Authorization: Bearer <REDACTED>" \
    -H 'Accept: application/json' \
    -H 'Content-Type: application/json' \
    https://192.168.0.24:6443/clusters/root:default:test/apis/authorization.k8s.io/v1/selfsubjectaccessreviews <<'EOF'
{
  "kind": "SelfSubjectAccessReview",
  "apiVersion": "authorization.k8s.io/v1",
  "spec": {
    "namespace": "default",
    "resourceAttributes": {
      "group": "apps",
      "resource": "deployment"
    }
  }
}
EOF
< HTTP/2 201
< audit-id: 7f143413-20e6-4174-bc9a-38694849880f
< cache-control: no-cache, private
< content-type: application/json
< x-kubernetes-pf-flowschema-uid:
< x-kubernetes-pf-prioritylevel-uid:
< content-length: 876
< date: Thu, 08 Sep 2022 18:49:20 GMT
<
{
  "kind": "SelfSubjectAccessReview",
  "apiVersion": "authorization.k8s.io/v1",
  "spec": {
    "resourceAttributes": {
      "group": "apps",
      "resource": "deployment"
    }
  },
  "status": {
    "allowed": true,
    "reason": "RBAC: allowed by ClusterRoleBinding \"system:kcp:clusterworkspace:admin\" of ClusterRole \"cluster-admin\" to Group \"system:kcp:clusterworkspace:admin\""
  }
* Connection #0 to host 192.168.0.24 left intact
}%
```

**Comment by s-urbaniak** [comment]
oh this looks interesting, grabbing this now.
