### ISSUE TITLE
bug: `workspace use` panic

### ISSUE THREAD

**Issue by mjudeikis** [kcp-dev/kcp#2073]
### Describe the bug

`kcp workspace use root:foo` panics with flowcontroll on `main`
```
[mjudeikis@unknown kcp]$ which kubectl-workspaces 
/go/src/github.com/kcp-dev/kcp/bin/kubectl-workspaces

[mjudeikis@unknown kcp]$ make build

[mjudeikis@unknown kcp]$ kubectl kcp workspace use root:foo
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1e6a65d]

goroutine 1 [running]:
golang.org/x/time/rate.(*Limiter).WaitN(0xc0006270e0, {0x0, 0x0}, 0x1)
        /go/pkg/mod/golang.org/x/time@v0.0.0-20220210224613-90d013bbcef8/rate/rate.go:234 +0x1bd
golang.org/x/time/rate.(*Limiter).Wait(...)
        /go/pkg/mod/golang.org/x/time@v0.0.0-20220210224613-90d013bbcef8/rate/rate.go:216
k8s.io/client-go/util/flowcontrol.(*tokenBucketRateLimiter).Wait(0xc0013e4280?, {0x0?, 0x0?})
        /go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/client-go@v0.0.0-20220915135949-eeba459ad2a1/util/flowcontrol/throttle.go:131 +0x2b
k8s.io/client-go/rest.(*Request).tryThrottleWithInfo(0xc0013dac60, {0x0, 0x0}, {0x0, 0x0})
        /go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/client-go@v0.0.0-20220915135949-eeba459ad2a1/rest/request.go:545 +0xba
k8s.io/client-go/rest.(*Request).tryThrottle(...)
        /go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/client-go@v0.0.0-20220915135949-eeba459ad2a1/rest/request.go:573
k8s.io/client-go/rest.(*Request).request(0xc0013dac60, {0x0, 0x0}, 0x0?)
        /go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/client-go@v0.0.0-20220915135949-eeba459ad2a1/rest/request.go:876 +0x24d
k8s.io/client-go/rest.(*Request).Do(0xc0013dac60, {0x0, 0x0})
        /go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/client-go@v0.0.0-20220915135949-eeba459ad2a1/rest/request.go:951 +0xc9
github.com/kcp-dev/kcp/pkg/client/clientset/versioned/typed/tenancy/v1beta1.(*workspaces).Get(0xc0013e4220, {0x0, 0x0}, {0x7ffda89c7063, 0x3}, {{{0x0, 0x0}, {0x0, 0x0}}, {0x0, ...}})
        /go/src/github.com/kcp-dev/kcp/pkg/client/clientset/versioned/typed/tenancy/v1beta1/workspace.go:78 +0x15a
github.com/kcp-dev/kcp/pkg/cliplugins/workspace/plugin.(*UseWorkspaceOptions).Run(0xc000da8f40, {0x0, 0x0})
        /go/src/github.com/kcp-dev/kcp/pkg/cliplugins/workspace/plugin/kubeconfig.go:231 +0xe6e
github.com/kcp-dev/kcp/pkg/cliplugins/workspace/cmd.New.func2(0xc000991180?, {0xc000de4f50?, 0x1?, 0x1?})
        /go/src/github.com/kcp-dev/kcp/pkg/cliplugins/workspace/cmd/cmd.go:106 +0x68
github.com/spf13/cobra.(*Command).execute(0xc000991180, {0xc000de4ec0, 0x1, 0x1})
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000990780)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
        /go/src/github.com/kcp-dev/kcp/cmd/kubectl-kcp/main.go:87 +0x5e5
```
works without kubectl:
```
[mjudeikis@unknown kcp]$ go run ./cmd/kubectl-workspaces/ use root:foo
Current workspace is "root:foo".
```

```
mjudeikis@unknown kcp]$ kubectl version 
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3+kcp-v0.8.0-154-g3ab2a86d95dc78", GitCommit:"3ab2a86d", GitTreeState:"clean", BuildDate:"2022-09-24T13:30:03Z", GoVersion:"go1.18.5", Compiler:"gc", Platform:"linux/amd64"}
```

### Steps To Reproduce

1. build `kubectl-workspace` from `main`
2. use with kubectl (1.24.3 was mine)
3. Use for any nested workspace (not root)

### Expected Behaviour

Should work :)

**Comment by mjudeikis** [comment]
took a random commit few days ago `4498ad7b6d86750af3906eb5ccc4c45aafc25b71` and it works :shrug:

**Comment by ncdc** [comment]
From the stack trace, the code that is panicking is

```go
case <-ctx.Done():
```

Somehow, `ctx` is nil (?). Not really sure how that is possible.

I'm not sure this is a with/without kubectl invocation issue. I think you'll only hit the panic if you get throttled. But I just hacked my local copy to throttle, and it isn't panicking.

If you're able to reproduce this reliably, please let us know. The exact git commit you're using for your CLI plugin would be helpful, along with steps to reproduce. Thanks!

/priority awaiting-more-evidence

**Comment by mjudeikis** [comment]
I just build `kubectl-workspaces` from `d6a0e24b889ac60b4d9cd347d851721062ce9aa2` (commit I was using when faced this first time) and it fails with the same error,  BUT current `main` does not. 

This so interesting I can't get my head around what is happening. Gonna try debug this particual commit locally to see if this give me something else.

**Comment by mjudeikis** [comment]
Tried tracking from start to end and looks like everywhere is `ctx` is passed right. But with this commit for me its quite consistent. The only plosible explanation I can think of is that at this commit we have shared memory somewhere and it overrides context object somwhere. And only in the nested worksapce case.

As now `main` is not showing this again, I'm tempted to close  this one if you can't replicate on `d6a0e24b889ac60b4d9cd347d851721062ce9aa2`. 

![Peek 2022-09-26 17-47](https://user-images.githubusercontent.com/3225744/192308168-b4782c2a-e148-414a-8b3a-1593ebacd70d.gif)

And we have enough details in here to re-open if this comes back again. 

Sorry, as puzzled as you are...

**Comment by mjudeikis** [comment]
lets close as this is not an issue on main anymore. But still mistery
