### ISSUE TITLE
Cluster wildcard: attempt to CRUD non-existent CRD panics

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#220]
**Describe the bug**
Doing a wildcard cluster operation against a CRD GVR that does not exist causes a panic.

**To Reproduce**
1. Start kcp
2. `k get --raw '/clusters/*/apis/foo.com/v1/blarg'`
3. Panic:

```
E1119 09:30:44.604917   82518 runtime.go:76] Observed a panic: runtime error: invalid memory address or nil pointer dereference
goroutine 5255 [running]:
k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1.1()
        /Users/angoldst/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20211118181850-ab2ca04a5894/pkg/server/filters/timeout.go:103 +0xb0
panic({0x315d500, 0x4fdb330})
        /usr/local/Cellar/go/1.17.2/libexec/src/runtime/panic.go:1038 +0x215
k8s.io/apiextensions-apiserver/pkg/apiserver.(*crdHandler).ServeHTTP(0xc0009f4000, {0xb5c02a8, 0xc00310d228}, 0xc00218f700)
        /Users/angoldst/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiextensions-apiserver@v0.0.0-20211118181850-ab2ca04a5894/pkg/apiserver/customresource_handler.go:353 +0xa96
```

**Expected behavior**
No panic

**Additional context**
This is a bug in kcp-dev/kubernetes. If https://github.com/kcp-dev/kubernetes/blob/ab2ca04a589440bf6326773b1d200f83dba68c32/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go#L297-L327 does not find the CRD, then `crd` stays nil.

The panic occurs at https://github.com/kcp-dev/kubernetes/blob/ab2ca04a589440bf6326773b1d200f83dba68c32/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go#L353 when we try to dereference crd:

```go
namespacedCRD, namespacedReq := crd.Spec.Scope == apiextensionsv1.NamespaceScoped, len(requestInfo.Namespace) > 0
```

**Comment by ncdc** [comment]
@jmprusi is working on this. Assigning to myself as GH won't let me assign.
