### ISSUE TITLE
go interface low-level code segfault

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#2207]
Happened in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/kcp-dev_kcp/2205/pull-ci-kcp-dev-kcp-main-e2e-multiple-runs/1582095144843218944 for #2205 but I doubt anything in there is causing this. And it only happened in 1 of 3 e2e runs.

```
        unexpected fault address 0x0
        fatal error: fault
        [signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x1522271]
        
        goroutine 11541 [running]:
        runtime.throw({0x44410c5?, 0x0?})
        	/usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc00129fd98 sp=0xc00129fd68 pc=0x1550511
        runtime.sigpanic()
        	/usr/local/go/src/runtime/signal_unix.go:825 +0x305 fp=0xc00129fde8 sp=0xc00129fd98 pc=0x1566ac5
        runtime.getitab(0x3ff8a20, 0x6874617000000065, 0xac?)
        	/usr/local/go/src/runtime/iface.go:40 +0x31 fp=0xc00129fe30 sp=0xc00129fde8 pc=0x1522271
        runtime.assertI2I2(0x4b5f1a8?, {0xc005d4ea90?, 0x9?})
        	/usr/local/go/src/runtime/iface.go:438 +0x3d fp=0xc00129fe60 sp=0xc00129fe30 pc=0x15232fd
        github.com/google/cel-go/interpreter.CostTracker.actualSize(...)
        	/go/pkg/mod/github.com/google/cel-go@v0.10.1/interpreter/runtimecost.go:167
        github.com/google/cel-go/interpreter.CostTracker.costCall({{0x4b30e20, 0xc00297f1d0}, 0xc000d62070, 0x3, {0xc00671b7c0, 0x0, 0x2}}, {0x7f99d5f13aa0?, 0xc0066ab710?}, {0xc00671b7c0, ...}, ...)
        	/go/pkg/mod/github.com/google/cel-go@v0.10.1/interpreter/runtimecost.go:123 +0xcd1 fp=0xc00129fef0 sp=0xc00129fe60 pc=0x3068871
        github.com/google/cel-go/interpreter.CostObserver.func1(0xc0066ab710?, {0x414b900?, 0xc0066ab710}, {0x4b5f1a8?, 0x67d7a68?})
        	/go/pkg/mod/github.com/google/cel-go@v0.10.1/interpreter/runtimecost.go:61 +0x39d fp=0xc0012a0000 sp=0xc00129fef0 pc=0x30678dd
        github.com/google/cel-go/interpreter.(*evalWatch).Eval(0xc004c57d40, {0x4b37cb0?, 0xc0066ab740?})
        	/go/pkg/mod/github.com/google/cel-go@v0.10.1/interpreter/interpretable.go:895 +0x83 fp=0xc0012a0048 sp=0xc0012a0000 pc=0x305eba3
        github.com/google/cel-go/cel.(*prog).Eval(0xc0038fb360, {0x3fbe6e0?, 0xc0066ab740})
        	/go/pkg/mod/github.com/google/cel-go@v0.10.1/cel/program.go:284 +0x27c fp=0xc0012a0138 sp=0xc0012a0048 pc=0x306f95c
        github.com/google/cel-go/cel.(*prog).ContextEval(0xc0038fb360, {0x4b5a520, 0xc005c99e60}, {0x3fcc9e0?, 0xc0066ab6b0})
        	/go/pkg/mod/github.com/google/cel-go@v0.10.1/cel/program.go:314 +0x3ba fp=0xc0012a0258 sp=0xc0012a0138 pc=0x307007a
        github.com/google/cel-go/cel.(*progGen).ContextEval(0xc00500be30, {0x4b5a520, 0xc005c99e60}, {0x3fcc9e0, 0xc0066ab6b0})
        	/go/pkg/mod/github.com/google/cel-go@v0.10.1/cel/program.go:387 +0x128 fp=0xc0012a02b0 sp=0xc0012a0258 pc=0x3070748
        k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel.(*Validator).validateExpressions(0xc0066c0190, {0x4b5a520, 0xc005c99e60}, 0x40?, 0xc003ab5ad0, {0x3f805c0?, 0xc006697a70?}, {0x3f805c0?, 0xc005cb25d0?}, 0x989680)
        	/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiextensions-apiserver@v0.0.0-20221005071841-6cfb7d485cbf/pkg/apiserver/schema/cel/validation.go:177 +0x712 fp=0xc0012a0530 sp=0xc0012a02b0 pc=0x30aba12
        k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel.(*Validator).Validate(0xc0066c0190, {0x4b5a520, 0xc005c99e60}, 0x0?, 0x0?, {0x3f805c0?, 0xc006697a70}, {0x3f805c0?, 0xc005cb25d0?}, 0x989680)
        	/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiextensions-apiserver@v0.0.0-20221005071841-6cfb7d485cbf/pkg/apiserver/schema/cel/validation.go:108 +0xc5 fp=0xc0012a0618 sp=0xc0012a0530 pc=0x30aaf25
        k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel.(*Validator).validateMap(0xc0066c0140, {0x4b5a520, 0xc005c99e60}, 0xc0066ab650, 0xc003ab5a20, 0xc003ab5a20?, 0x3f805c0?, 0xc006697a40?)
        	/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiextensions-apiserver@v0.0.0-20221005071841-6cfb7d485cbf/pkg/apiserver/schema/cel/validation.go:297 +0x67b fp=0xc0012a0910 sp=0xc0012a0618 pc=0x30ad6db
        k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel.(*Validator).Validate(0xc0066c0140, {0x4b5a520, 0xc005c99e60}, 0x1?, 0xc0066ab5f0?, {0x3f805c0?, 0xc006697a40}, {0x3f805c0?, 0xc005cb25a0?}, 0x989680)
        	/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiextensions-apiserver@v0.0.0-20221005071841-6cfb7d485cbf/pkg/apiserver/schema/cel/validation.go:122 +0x171 fp=0xc0012a09f8 sp=0xc0012a0910 pc=0x30aafd1
        k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel.(*Validator).validateMap(0xc0029c2910, {0x4b5a520, 0xc005c99e60}, 0x0, 0xc004f32c60, 0xc004f32c60?, 0x3f805c0?, 0xc006697680?)
        	/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiextensions-apiserver@v0.0.0-20221005071841-6cfb7d485cbf/pkg/apiserver/schema/cel/validation.go:297 +0x67b fp=0xc0012a0cf0 sp=0xc0012a09f8 pc=0x30ad6db
        k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel.(*Validator).Validate(0xc0029c2910, {0x4b5a520, 0xc005c99e60}, 0x4b3dbb0?, 0xc005cb4018?, {0x3f805c0?, 0xc006697680}, {0x3f805c0?, 0xc005cb2570?}, 0x989680)
        	/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiextensions-apiserver@v0.0.0-20221005071841-6cfb7d485cbf/pkg/apiserver/schema/cel/validation.go:122 +0x171 fp=0xc0012a0dd8 sp=0xc0012a0cf0 pc=0x30aafd1
        k8s.io/apiextensions-apiserver/pkg/registry/customresource.statusStrategy.ValidateUpdate({{{0x4b44d70, 0xc0003698e0}, {0x4b35e00, 0x6932040}, 0x0, {0x0, {{...}, {...}, {...}}, 0xc000572a80, ...}, ...}}, ...)
        	/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiextensions-apiserver@v0.0.0-20221005071841-6cfb7d485cbf/pkg/registry/customresource/status_strategy.go:118 +0x3bf fp=0xc0012a0f48 sp=0xc0012a0dd8 pc=0x312de3f
        k8s.io/apiextensions-apiserver/pkg/registry/customresource.(*statusStrategy).ValidateUpdate(0x4b3dbb0?, {0x4b5a520?, 0xc005c99e60?}, {0x4b3dbb0?, 0xc0065944f8?}, {0x4b3dbb0?, 0xc005cb4018?})
        	<autogenerated>:1 +0xca fp=0xc0012a1108 sp=0xc0012a0f48 pc=0x31370aa
        k8s.io/apiserver/pkg/registry/rest.BeforeUpdate({0x4b6d098?, 0xc004ca1200}, {0x4b5a520, 0xc005c99e60}, {0x4b3dbb0, 0xc0065944f8}, {0x4b3dbb0?, 0xc005cb4018})
        	/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20221005071841-6cfb7d485cbf/pkg/registry/rest/update.go:172 +0x60d fp=0xc0012a12a8 sp=0xc0012a1108 pc=0x28989cd
        k8s.io/apiserver/pkg/registry/generic/registry.(*Store).Update.func1({0x4b3dbb0, 0xc005cb4018}, {0xc0cb8b1391d4130b?, 0x25edb27c0?})
        	/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20221005071841-6cfb7d485cbf/pkg/registry/generic/registry/store.go:657 +0x597 fp=0xc0012a1510 sp=0xc0012a12a8 pc=0x2dd6a37
        k8s.io/apiserver/pkg/storage/etcd3.(*store).updateState(0xc003773b00, 0xc004f199e0?, 0x53?)
        	/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20221005071841-6cfb7d485cbf/pkg/storage/etcd3/store.go:948 +0x3e fp=0xc0012a1570 sp=0xc0012a1510 pc=0x2a8317e
        k8s.io/apiserver/pkg/storage/etcd3.(*store).GuaranteedUpdate(0xc003773b00, {0x4b5a520, 0xc005c99e60}, {0xc0020d06e0, 0x4a}, {0x4b3dbb0?, 0xc005cb4010}, 0x1, 0xc0059b9cf0?, 0xc005c97080, ...)
        	/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20221005071841-6cfb7d485cbf/pkg/storage/etcd3/store.go:402 +0x78e fp=0xc0012a1c20 sp=0xc0012a1570 pc=0x2a7e06e
        k8s.io/apiserver/pkg/storage/cacher.(*Cacher).GuaranteedUpdate(0xc004f48900, {0x4b5a520, 0xc005c99e60}, {0xc0020d06e0, 0x4a}, {0x4b3dbb0, 0xc005cb4010}, 0xa8?, 0x4382780?, 0xc005c97080, ...)
        	/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20221005071841-6cfb7d485cbf/pkg/storage/cacher/cacher.go:738 +0x122 fp=0xc0012a1cb0 sp=0xc0012a1c20 pc=0x2dc3a82
        k8s.io/apiserver/pkg/registry/generic/registry.(*DryRunnableStorage).GuaranteedUpdate(0xb?, {0x4b5a520?, 0xc005c99e60?}, {0xc0020d06e0?, 0x2?}, {0x4b3dbb0?, 0xc005cb4010?}, 0x10?, 0x444e022?, 0xc005c97080, ...)
        	/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20221005071841-6cfb7d485cbf/pkg/registry/generic/registry/dryrun.go:93 +0x1c7 fp=0xc0012a1d28 sp=0xc0012a1cb0 pc=0x2dd2cc7
        k8s.io/apiserver/pkg/registry/generic/registry.(*Store).Update(0xc002155b80, {0x4b5a520?, 0xc005c99e60}, {0xc0020d05c8, 0x13}, {0x4b3e5b0?, 0xc005cb24b0}, 0xc005a30aa0, 0xc005ca6580, 0x0, ...)
        	/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20221005071841-6cfb7d485cbf/pkg/registry/generic/registry/store.go:552 +0x508 fp=0xc0012a1e28 sp=0xc0012a1d28 pc=0x2dd6188
        k8s.io/apiextensions-apiserver/pkg/registry/customresource.(*StatusREST).Update(0x4b5a4e8?, {0x4b5a520?, 0xc005c99e60?}, {0xc0020d05c8?, 0x3d9e380?}, {0x4b3e5b0?, 0xc005cb24b0?}, 0x1525405?, 0xe?, 0x0, ...)
        	/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiextensions-apiserver@v0.0.0-20221005071841-6cfb7d485cbf/pkg/registry/customresource/etcd.go:224 +0x57 fp=0xc0012a1e90 sp=0xc0012a1e28 pc=0x312bab7
        k8s.io/apiserver/pkg/endpoints/handlers.(*patcher).patchResource.func2()
        	/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20221005071841-6cfb7d485cbf/pkg/endpoints/handlers/patch.go:685 +0xa7 fp=0xc0012a1f18 sp=0xc0012a1e90 pc=0x2b23947
        k8s.io/apiserver/pkg/endpoints/handlers.(*patcher).patchResource.func3()
        	/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20221005071841-6cfb7d485cbf/pkg/endpoints/handlers/patch.go:691 +0x38 fp=0xc0012a1f80 sp=0xc0012a1f18 pc=0x2b23658
        k8s.io/apiserver/pkg/endpoints/handlers/finisher.finishRequest.func1()
        	/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20221005071841-6cfb7d485cbf/pkg/endpoints/handlers/finisher/finisher.go:117 +0x8f fp=0xc0012a1fe0 sp=0xc0012a1f80 pc=0x2b10b4f
        runtime.goexit()
        	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0012a1fe8 sp=0xc0012a1fe0 pc=0x15841a1
        created by k8s.io/apiserver/pkg/endpoints/handlers/finisher.finishRequest
        	/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20221005071841-6cfb7d485cbf/pkg/endpoints/handlers/finisher/finisher.go:92 +0xde
```

**Comment by ncdc** [comment]
Weird, this appears to be an issue with a go type assertion. Should never happen... Only issue I've found so far was from 2017 - https://github.com/golang/go/issues/20901 - and it was never reproducible.

**Comment by nrb** [comment]
Per community meeting, we'll keep this open to track flakes in case it happens again.
