### ISSUE TITLE
Panic when using KCP

### ISSUE THREAD

**Issue by guillaumerose** [kcp-dev/kcp#327]
**Describe the bug**

While playing maybe a little bit too hard with KCP. I ended up with:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x21f1635]

goroutine 55290 [running]:
k8s.io/apiserver/pkg/util/webhook.(*ClientManager).HookClient.func2({0x3998a60, 0xc003b8e4e0}, {0x34c5770, 0x3}, {0xc004dc0500, 0x31})
	/Users/guillaumerose/.gvm/pkgsets/go1.17.1/global/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20211213195413-bd3dfca555cd/pkg/util/webhook/client.go:190 +0xd5
net/http.(*Transport).dial(0xc003b8e4e0, {0x3998a60, 0xc003b8e4e0}, {0x34c5770, 0x1}, {0xc004dc0500, 0x8})
	/Users/guillaumerose/.gvm/gos/go1.17.1/src/net/http/transport.go:1166 +0xda
net/http.(*Transport).dialConn(0xc0071dde00, {0x3998a60, 0xc003b8e4e0}, {{}, 0x0, {0xc00815ed80, 0x5}, {0xc004dc0500, 0x31}, 0x0})
	/Users/guillaumerose/.gvm/gos/go1.17.1/src/net/http/transport.go:1604 +0x845
net/http.(*Transport).dialConnFor(0x0, 0xc00a5d2840)
	/Users/guillaumerose/.gvm/gos/go1.17.1/src/net/http/transport.go:1446 +0xb0
created by net/http.(*Transport).queueForDial
	/Users/guillaumerose/.gvm/gos/go1.17.1/src/net/http/transport.go:1415 +0x3d7
```

I am using 871852b75e2f363ec7b21d87b39805f17a34a872 (Tue Dec 14 rev)

**To Reproduce**
1. Run Tekton triggers controller on a physical cluster talking to KCP
2. Install github example from triggers samples. Be sure to remove references to the cluster interceptor in the event listener.

TBH, my setup is really unusual. It's not really easy to describe. The script so far to run all this: https://github.com/openshift-pipelines/pipelines-service/pull/2

**Expected behavior**

No panic :)

**Comment by guillaumerose** [comment]
It happens after a ConversionReview request:
```
I1216 09:44:25.264590   81863 request.go:1250] Request Body: {"kind":"ConversionReview","apiVersion":"apiextensions.k8s.io/v1beta1","request":{"uid":"46d50e2b-5117-4584-8cf9-c44baf96a0f2","desiredAPIVersion":"tekton.dev/v1beta1","objects":[{"apiVersion":"tekton.dev/v1alpha1","kind":"TaskRun","metadata":{"creationTimestamp":"2021-12-16T08:44:25Z","generateName":"github-run-","generation":1,"labels":{"triggers.tekton.dev/eventlistener":"github-listener","triggers.tekton.dev/trigger":"github-listener","triggers.tekton.dev/triggers-eventid":"3ba5de44-eeb9-43c5-b187-4319a785ac1e"},"managedFields":[{"apiVersion":"tekton.dev/v1alpha1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:generateName":{},"f:labels":{".":{},"f:triggers.tekton.dev/eventlistener":{},"f:triggers.tekton.dev/trigger":{},"f:triggers.tekton.dev/triggers-eventid":{}}},"f:spec":{".":{},"f:inputs":{".":{},"f:resources":{}},"f:taskSpec":{".":{},"f:inputs":{".":{},"f:resources":{}},"f:steps":{}}}},"manager":"eventlistenersink","operation":"Update","time":"2021-12-16T08:44:25Z"}],"name":"github-run-bp7vl","namespace":"default","uid":"fc568063-4861-47c7-8b8e-1d4a96836833"},"spec":{"inputs":{"resources":[{"name":"source","resourceSpec":{"params":[{"name":"revision","value":"28911bbb5a3e2ea034daf1f6be0a822d50e31e73"},{"name":"url","value":"https://github.com/tektoncd/triggers.git"}],"type":"git"}}]},"taskSpec":{"inputs":{"resources":[{"name":"source","type":"git"}]},"steps":[{"image":"ubuntu","script":"#! /bin/bash\nls -al $(inputs.resources.source.path)\n"}]}}}]},"response":{"uid":"","convertedObjects":null,"result":{"metadata":{}}}}
```

**Comment by stevekuznetsov** [comment]
Webhooks should not be turned on in `kcp` - @imjasonh maybe we did not turn them off well enough?

**Comment by ncdc** [comment]
That's from the CRD conversion webhook flow

**Comment by ncdc** [comment]
Which needs a way to resolve the Service defined in the CRD spec for conversion to endpoints to make a conversion request. And we've disabled/not set the serviceResolver, which is what's nil in the panic.

**Comment by stevekuznetsov** [comment]
Right, so webhooks of any flavor should be off - including CRD conversion?

**Comment by ncdc** [comment]
For now, given that we don't have Services implemented, I'd say yes.

**Comment by ncdc** [comment]
Will see if I can provide a better solution here.

**Comment by ncdc** [comment]
Will be fixed when https://github.com/kcp-dev/kubernetes/pull/31 is merged and then we bump kube in kcp

**Comment by pweil-** [comment]
doing some older issue triage.  Doesn't look like any movement lately on https://github.com/kcp-dev/kubernetes/pull/31 @ncdc.  Still intending to merge that?

**Comment by ncdc** [comment]
It's actually in kcp now (https://github.com/kcp-dev/kcp/blob/5da15ce28f1671e72b175acf528aa6eb62d1a899/pkg/server/server.go#L312). We can close this and that other PR.
