### ISSUE TITLE
Panic when using kubectl describe deploy

### ISSUE THREAD

**Issue by guillaumerose** [kcp-dev/kcp#341]
**Describe the bug**

```
I1220 11:25:19.202843   40156 round_trippers.go:435] curl -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.22.2 (darwin/amd64) kubernetes/8b5a191" -H "Authorization: Bearer <masked>" 'https://[::1]:6443/apis/apps/v1/namespaces/default/replicasets?labelSelector=app.kubernetes.io%2Fmanaged-by%3DEventListener%2Capp.kubernetes.io%2Fpart-of%3DTriggers%2Ceventlistener%3Dgithub-listener%2Ckcp.dev%2Fcluster%3Dlocal&limit=500'
I1220 11:25:19.203250   40156 round_trippers.go:454] GET https://[::1]:6443/apis/apps/v1/namespaces/default/replicasets?labelSelector=app.kubernetes.io%2Fmanaged-by%3DEventListener%2Capp.kubernetes.io%2Fpart-of%3DTriggers%2Ceventlistener%3Dgithub-listener%2Ckcp.dev%2Fcluster%3Dlocal&limit=500 404 Not Found in 0 milliseconds
I1220 11:25:19.203266   40156 round_trippers.go:460] Response Headers:
I1220 11:25:19.203272   40156 round_trippers.go:463]     Date: Mon, 20 Dec 2021 10:25:19 GMT
I1220 11:25:19.203277   40156 round_trippers.go:463]     Audit-Id: deef2911-c634-4edc-8072-cd7ec99eed5e
I1220 11:25:19.203281   40156 round_trippers.go:463]     Cache-Control: no-cache, private
I1220 11:25:19.203284   40156 round_trippers.go:463]     Content-Type: text/plain; charset=utf-8
I1220 11:25:19.203288   40156 round_trippers.go:463]     X-Content-Type-Options: nosniff
I1220 11:25:19.203291   40156 round_trippers.go:463]     Content-Length: 19
I1220 11:25:19.203306   40156 request.go:1181] Response Body: 404 page not found
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10c4bd664]

goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/describe.describeDeployment.func1(0x10cf6ddc8, 0xc0005ce0b0, 0xc00079c720, 0x0)
	/private/tmp/kubernetes-cli-20210929-62308-14uhcvu/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/describe/describe.go:4203 +0x3c4
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/describe.tabbedString(0xc0005b1a08, 0x10cfb9f18, 0xc0003242a0, 0x0, 0x0)
	/private/tmp/kubernetes-cli-20210929-62308-14uhcvu/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/describe/describe.go:5213 +0xbc
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/describe.describeDeployment(0xc000101b00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc000162bd0, 0x0, 0x0, ...)
	/private/tmp/kubernetes-cli-20210929-62308-14uhcvu/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/describe/describe.go:4195 +0x145
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/describe.(*DeploymentDescriber).Describe(0xc0002fae40, 0x10c6f3b4d, 0x7, 0x7ffee4be16b8, 0x12, 0x1, 0x1f4, 0x0, 0x0, 0x10cd2a000, ...)
	/private/tmp/kubernetes-cli-20210929-62308-14uhcvu/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/describe/describe.go:4187 +0x1b1
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/describe.(*DescribeOptions).Run(0xc0004d30e0, 0x0, 0x10cf436e0)
	/private/tmp/kubernetes-cli-20210929-62308-14uhcvu/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/describe/describe.go:193 +0x519
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/describe.NewCmdDescribe.func1(0xc0004d4280, 0xc00068e930, 0x2, 0x3)
	/private/tmp/kubernetes-cli-20210929-62308-14uhcvu/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/describe/describe.go:113 +0x9f
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc0004d4280, 0xc00068e900, 0x3, 0x3, 0xc0004d4280, 0xc00068e900)
	/private/tmp/kubernetes-cli-20210929-62308-14uhcvu/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:856 +0x2c2
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0004c8f00, 0xc0000521e0, 0xc00003c0a0, 0x5)
	/private/tmp/kubernetes-cli-20210929-62308-14uhcvu/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:960 +0x375
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/private/tmp/kubernetes-cli-20210929-62308-14uhcvu/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:897
main.main()
	_output/local/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:49 +0x21d
```

**To Reproduce**
1. Install a deployment
2. Run `kubectl describe deploy el-github-listener --v=9`

**Expected behavior**

Don't panic

**Additional context**

I guess it's something to fix in kubectl?

**Comment by stevekuznetsov** [comment]
In discovery, likely something @ncdc wants to look at when he's back in January. Thanks for the bug report!

**Comment by kylape** [comment]
Did some poking, and I was able to reproduce on an Openshift and Kind cluster by running `oc describe deploy --v=9` with a deployment name that does not exist.  So I believe this is a `kubectl` issue.

**Comment by stevekuznetsov** [comment]
If we have an upstream issue to link, we should close this one!

**Comment by kylape** [comment]
I'll find a link to a kubectl issue :+1:

**Comment by kylape** [comment]
Okay, so I misread the `kubectl --v=9` output :man_facepalming: .  It prints a thread dump every time there's a nonzero exit status, e.g. when the requested name does not exist.  I wrongly assumed this was a segfault.

Given that, I tried checking out a version of kcp ~1 month old (934530e607d85c5ccad1835d0f1e2d8f0a825552) and downloaded kubectl v1.22.2 (to match the version reported by @guillaumerose), and did the following steps:

```
rm -rf .kcp
go run ./cmd/kcp start
```

In another window:

```
$ kubectl create -f contrib/crds/apps/apps_deployments.yaml
$ kubectl create ns default
$ kubectl create -f deployment.yml
deployment.apps/test created
$ kubectl describe deployments test --v=9  # describe existing deployment
$ kubectl describe deployments testt --v=9  # describe non-existent deployment
```
And I could never get a segfault.

I also tried with the latest version of kcp and kubectl v1.22.3 with no segfault.

Based on the segfault stack trace, it looks like a nil pointer dereference on this line: https://github.com/kubernetes/kubectl/blob/v0.22.2/pkg/describe/describe.go#L4203

The only dereference was for `d.Spec.Replicas`, so I tried unsetting that in my test deployment, and voila! segfault.

So I _think_ the problem here is that the defaulting behavior in a normal k8s apiserver is not hooked up yet for kcp.

**Comment by ncdc** [comment]
@sttts this is another example of built-in type defaulting logic (deployment spec.replicas is a pointer that defaults to 1 when nil, in code). Should we file an upstream issue + PR to set an openapi comment tag to have the default be 1? Are there any negative implications of doing so?
