### ISSUE TITLE
Crash when syncer is no longer able to connect to a physical cluster

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#455]
**Describe the bug**
kcp crashes when it is unable to connect to a previously-registered physical cluster.

**To Reproduce**
1. `make build`
2. `./bin/kcp start --install-cluster-controller --install-namespace-scheduler --install-workspace-scheduler --auto-publish-apis --resources-to-sync="ingresses.networking.k8s.io,deployments.apps,services" --push-mode --token-auth-file contrib/demo/workspaceKubectlPlugin-script/kcp-tokens`
3. Start a physical cluster (e.g. kind)
4. Create a cluster.yaml for the physical cluster and apply it
5. Let the cluster be reconciled/synced at least once
6. Shut down the physical cluster
7. Wait for kcp to crash (it doesn't take all that long)

**Expected behavior**
No crash

**Additional context**
Here's the stack trace (testing from commit a7be6c6):

```
I0207 21:51:05.674008   82886 cluster.go:43] reconciling cluster "kind-us-east1"
I0207 21:51:05.680872   82886 syncer.go:165] Set up informer for /v1, Resource=namespaces
I0207 21:51:05.680899   82886 syncer.go:165] Set up informer for /v1, Resource=services
I0207 21:51:05.680911   82886 syncer.go:165] Set up informer for apps/v1, Resource=deployments
I0207 21:51:05.680922   82886 syncer.go:165] Set up informer for networking.k8s.io/v1, Resource=ingresses
E0207 21:51:15.412338   82886 memcache.go:179] couldn't get current server API group list: Get "https://127.0.0.1:53373/api?timeout=32s": read tcp 127.0.0.1:61746->127.0.0.1:53373: read: connection reset by peer
E0207 21:51:15.412364   82886 discovery.go:112] error mapping resource "ingresses.networking.k8s.io": Get "https://127.0.0.1:53373/api?timeout=32s": read tcp 127.0.0.1:61746->127.0.0.1:53373: read: connection reset by peer
E0207 21:51:15.731331   82886 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 3751 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x3192440, 0x50ce440})
        /Users/angoldst/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20220203192237-6b61675b7950/pkg/util/runtime/runtime.go:74 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc00903dc20})
        /Users/angoldst/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20220203192237-6b61675b7950/pkg/util/runtime/runtime.go:48 +0x75
panic({0x3192440, 0x50ce440})
        /usr/local/Cellar/go/1.17.6/libexec/src/runtime/panic.go:1038 +0x215
github.com/kcp-dev/kcp/pkg/syncer.(*Controller).Stop(0xc009684080)
        /Users/angoldst/go/src/github.com/kcp-dev/kcp/pkg/syncer/syncer.go:289 +0x32
github.com/kcp-dev/kcp/pkg/syncer.StartSyncer({0x39f04b0, 0xc002f0a080}, 0x6, 0x4, 0xc0090e9590, {0xc00798e7d0, 0xd}, {0xc00798e72b, 0x5}, 0x2)
        /Users/angoldst/go/src/github.com/kcp-dev/kcp/pkg/syncer/syncer.go:80 +0x1cc
github.com/kcp-dev/kcp/pkg/reconciler/cluster.(*Controller).reconcile(0xc001726120, {0x39f04b0, 0xc002f0a080}, 0xc0090d46e0)
        /Users/angoldst/go/src/github.com/kcp-dev/kcp/pkg/reconciler/cluster/cluster.go:142 +0x101e
github.com/kcp-dev/kcp/pkg/reconciler/cluster.(*Controller).process(0xc001726120, {0x39f04b0, 0xc002f0a080}, {0xc003b336e0, 0x15})
        /Users/angoldst/go/src/github.com/kcp-dev/kcp/pkg/reconciler/cluster/controller.go:277 +0x137
github.com/kcp-dev/kcp/pkg/reconciler/cluster.(*Controller).processNextWorkItem(0xc001726120, {0x39f04b0, 0xc002f0a080})
        /Users/angoldst/go/src/github.com/kcp-dev/kcp/pkg/reconciler/cluster/controller.go:255 +0x11c
github.com/kcp-dev/kcp/pkg/reconciler/cluster.(*Controller).startWorker(...)
        /Users/angoldst/go/src/github.com/kcp-dev/kcp/pkg/reconciler/cluster/controller.go:239
github.com/kcp-dev/kcp/pkg/reconciler/cluster.(*PreparedController).Start.func1()
        /Users/angoldst/go/src/github.com/kcp-dev/kcp/pkg/reconciler/cluster/controller.go:235 +0x4a
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xbf22438)
        /Users/angoldst/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20220203192237-6b61675b7950/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc002ae75c0, {0x39a1a20, 0xc003ac51d0}, 0x1, 0xc002ae75c0)
        /Users/angoldst/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20220203192237-6b61675b7950/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc002f0a080, 0x989680, 0x0, 0x80, 0x0)
        /Users/angoldst/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20220203192237-6b61675b7950/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /Users/angoldst/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20220203192237-6b61675b7950/pkg/util/wait/wait.go:90
github.com/kcp-dev/kcp/pkg/reconciler/cluster.(*PreparedController).Start(0xc00068fc98, {0x39f04b0, 0xc002f0a080})
        /Users/angoldst/go/src/github.com/kcp-dev/kcp/pkg/reconciler/cluster/controller.go:235 +0x21b
created by github.com/kcp-dev/kcp/pkg/server.(*Server).installClusterController.func1
        /Users/angoldst/go/src/github.com/kcp-dev/kcp/pkg/server/controllers.go:252 +0x4e5
I0207 21:51:15.744231   82886 panic.go:1038] Shutting down Cluster controller
E0207 21:51:15.744304   82886 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 3751 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x3192440, 0x50ce440})
        /Users/angoldst/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20220203192237-6b61675b7950/pkg/util/runtime/runtime.go:74 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc001333220})
        /Users/angoldst/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20220203192237-6b61675b7950/pkg/util/runtime/runtime.go:48 +0x75
panic({0x3192440, 0x50ce440})
        /usr/local/Cellar/go/1.17.6/libexec/src/runtime/panic.go:1038 +0x215
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc00903dc20})
        /Users/angoldst/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20220203192237-6b61675b7950/pkg/util/runtime/runtime.go:55 +0xd8
panic({0x3192440, 0x50ce440})
        /usr/local/Cellar/go/1.17.6/libexec/src/runtime/panic.go:1038 +0x215
github.com/kcp-dev/kcp/pkg/syncer.(*Controller).Stop(0xc009684080)
        /Users/angoldst/go/src/github.com/kcp-dev/kcp/pkg/syncer/syncer.go:289 +0x32
github.com/kcp-dev/kcp/pkg/syncer.StartSyncer({0x39f04b0, 0xc002f0a080}, 0x6, 0x4, 0xc0090e9590, {0xc00798e7d0, 0xd}, {0xc00798e72b, 0x5}, 0x2)
        /Users/angoldst/go/src/github.com/kcp-dev/kcp/pkg/syncer/syncer.go:80 +0x1cc
github.com/kcp-dev/kcp/pkg/reconciler/cluster.(*Controller).reconcile(0xc001726120, {0x39f04b0, 0xc002f0a080}, 0xc0090d46e0)
        /Users/angoldst/go/src/github.com/kcp-dev/kcp/pkg/reconciler/cluster/cluster.go:142 +0x101e
github.com/kcp-dev/kcp/pkg/reconciler/cluster.(*Controller).process(0xc001726120, {0x39f04b0, 0xc002f0a080}, {0xc003b336e0, 0x15})
        /Users/angoldst/go/src/github.com/kcp-dev/kcp/pkg/reconciler/cluster/controller.go:277 +0x137
github.com/kcp-dev/kcp/pkg/reconciler/cluster.(*Controller).processNextWorkItem(0xc001726120, {0x39f04b0, 0xc002f0a080})
        /Users/angoldst/go/src/github.com/kcp-dev/kcp/pkg/reconciler/cluster/controller.go:255 +0x11c
github.com/kcp-dev/kcp/pkg/reconciler/cluster.(*Controller).startWorker(...)
        /Users/angoldst/go/src/github.com/kcp-dev/kcp/pkg/reconciler/cluster/controller.go:239
github.com/kcp-dev/kcp/pkg/reconciler/cluster.(*PreparedController).Start.func1()
        /Users/angoldst/go/src/github.com/kcp-dev/kcp/pkg/reconciler/cluster/controller.go:235 +0x4a
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xbf22438)
        /Users/angoldst/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20220203192237-6b61675b7950/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc002ae75c0, {0x39a1a20, 0xc003ac51d0}, 0x1, 0xc002ae75c0)
        /Users/angoldst/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20220203192237-6b61675b7950/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc002f0a080, 0x989680, 0x0, 0x80, 0x0)
        /Users/angoldst/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20220203192237-6b61675b7950/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /Users/angoldst/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20220203192237-6b61675b7950/pkg/util/wait/wait.go:90
github.com/kcp-dev/kcp/pkg/reconciler/cluster.(*PreparedController).Start(0xc00068fc98, {0x39f04b0, 0xc002f0a080})
        /Users/angoldst/go/src/github.com/kcp-dev/kcp/pkg/reconciler/cluster/controller.go:235 +0x21b
created by github.com/kcp-dev/kcp/pkg/server.(*Server).installClusterController.func1
        /Users/angoldst/go/src/github.com/kcp-dev/kcp/pkg/server/controllers.go:252 +0x4e5
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2bde252]

goroutine 3751 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc001333220})
        /Users/angoldst/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20220203192237-6b61675b7950/pkg/util/runtime/runtime.go:55 +0xd8
panic({0x3192440, 0x50ce440})
        /usr/local/Cellar/go/1.17.6/libexec/src/runtime/panic.go:1038 +0x215
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc00903dc20})
        /Users/angoldst/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20220203192237-6b61675b7950/pkg/util/runtime/runtime.go:55 +0xd8
panic({0x3192440, 0x50ce440})
        /usr/local/Cellar/go/1.17.6/libexec/src/runtime/panic.go:1038 +0x215
github.com/kcp-dev/kcp/pkg/syncer.(*Controller).Stop(0xc009684080)
        /Users/angoldst/go/src/github.com/kcp-dev/kcp/pkg/syncer/syncer.go:289 +0x32
github.com/kcp-dev/kcp/pkg/syncer.StartSyncer({0x39f04b0, 0xc002f0a080}, 0x6, 0x4, 0xc0090e9590, {0xc00798e7d0, 0xd}, {0xc00798e72b, 0x5}, 0x2)
        /Users/angoldst/go/src/github.com/kcp-dev/kcp/pkg/syncer/syncer.go:80 +0x1cc
github.com/kcp-dev/kcp/pkg/reconciler/cluster.(*Controller).reconcile(0xc001726120, {0x39f04b0, 0xc002f0a080}, 0xc0090d46e0)
        /Users/angoldst/go/src/github.com/kcp-dev/kcp/pkg/reconciler/cluster/cluster.go:142 +0x101e
github.com/kcp-dev/kcp/pkg/reconciler/cluster.(*Controller).process(0xc001726120, {0x39f04b0, 0xc002f0a080}, {0xc003b336e0, 0x15})
        /Users/angoldst/go/src/github.com/kcp-dev/kcp/pkg/reconciler/cluster/controller.go:277 +0x137
github.com/kcp-dev/kcp/pkg/reconciler/cluster.(*Controller).processNextWorkItem(0xc001726120, {0x39f04b0, 0xc002f0a080})
        /Users/angoldst/go/src/github.com/kcp-dev/kcp/pkg/reconciler/cluster/controller.go:255 +0x11c
github.com/kcp-dev/kcp/pkg/reconciler/cluster.(*Controller).startWorker(...)
        /Users/angoldst/go/src/github.com/kcp-dev/kcp/pkg/reconciler/cluster/controller.go:239
github.com/kcp-dev/kcp/pkg/reconciler/cluster.(*PreparedController).Start.func1()
        /Users/angoldst/go/src/github.com/kcp-dev/kcp/pkg/reconciler/cluster/controller.go:235 +0x4a
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xbf22438)
        /Users/angoldst/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20220203192237-6b61675b7950/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc002ae75c0, {0x39a1a20, 0xc003ac51d0}, 0x1, 0xc002ae75c0)
        /Users/angoldst/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20220203192237-6b61675b7950/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc002f0a080, 0x989680, 0x0, 0x80, 0x0)
        /Users/angoldst/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20220203192237-6b61675b7950/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /Users/angoldst/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20220203192237-6b61675b7950/pkg/util/wait/wait.go:90
github.com/kcp-dev/kcp/pkg/reconciler/cluster.(*PreparedController).Start(0xc00068fc98, {0x39f04b0, 0xc002f0a080})
        /Users/angoldst/go/src/github.com/kcp-dev/kcp/pkg/reconciler/cluster/controller.go:235 +0x21b
created by github.com/kcp-dev/kcp/pkg/server.(*Server).installClusterController.func1
        /Users/angoldst/go/src/github.com/kcp-dev/kcp/pkg/server/controllers.go:252 +0x4e5
 ```

**Comment by ncdc** [comment]
Would suggest that we set up context cancelFuncs when creating the syncers, and store the cancelFuncs in the map so the cluster controller can call them, rather than trying to call Stop
