### ISSUE TITLE
Panic when using `kcp -h`

### ISSUE THREAD

**Issue by guillaumerose** [kcp-dev/kcp#500]
**Describe the bug**

```
./kcp -h
KCP is the easiest way to manage Kubernetes applications against one or more clusters, by giving you a personal control plane that schedules your workloads onto one or many clusters, and making it simple to pick up and move. Advanced use cases including spreading your apps across clusters for resiliency, scheduling batch workloads onto clusters with free capacity, and enabling collaboration for individual teams without having access to the underlying clusters.

To get started, launch a new cluster with 'kcp start', which will initialize your personal control plane and write an admin kubeconfig file to disk.


Usage:
  kcp [flags]

Most important flags:

      --etcd-servers strings                                                                                                                                                        
                List of etcd servers to connect with (scheme://ip:port), comma separated. By default an embedded etcd server is started. (default [embedded])
      --run-controllers                                                                                                                                                             
                Run the controllers in-process (default true)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x250 pc=0x11a4934]

goroutine 1 [running]:
github.com/spf13/cobra.(*Command).CommandPath(0xc0008a8560)
	/Users/guillaumerose/gomod/kcp/vendor/github.com/spf13/cobra/command.go:1238 +0x14
main.setPartialUsageAndHelpFunc.func2(0xc000a1ea00, {0xc0001a0010, 0x1, 0x1})
	/Users/guillaumerose/gomod/kcp/cmd/kcp/help.go:46 +0x1dc
github.com/spf13/cobra.(*Command).ExecuteC(0xc000a1ea00)
	/Users/guillaumerose/gomod/kcp/vendor/github.com/spf13/cobra/command.go:979 +0x558
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/guillaumerose/gomod/kcp/vendor/github.com/spf13/cobra/command.go:902
main.main()
	/Users/guillaumerose/gomod/kcp/cmd/kcp/kcp.go:142 +0x548

```

**To Reproduce**
1. Run `kcp -h`

**Additional context**

Revision: 986710c754ed0dac9ae1525661de931e5dd7c0cc (main as of today)

**Comment by slaskawi** [comment]
Let me have a look at this one. It sounds like a perfect first-timer issue.

**Comment by pweil-** [comment]
> Let me have a look at this one. It sounds like a perfect first-timer issue.

All yours.  I'll add it to the current milestone.  Thanks for volunteering 👍
